name: Publish to pub.dev

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

permissions:
  checks: write
  contents: write

env:
  # Actions will be forced to run with Node.js 24 by default starting June 2nd, 2026.
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  publish:
    environment: pub.dev
    permissions:
      id-token: write # This is required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1

      - name: Install dependencies
        run: dart pub get

      - name: Run tests
        run: dart test

      - name: Publish
        run: dart pub publish --force
